### ISSUE TITLE
bug: unable to select from empty native table (memory store)

### ISSUE THREAD

**Issue by adhish20** [GlareDB/glaredb#1658]
## Description

ERROR:  Error during planning: Unable to fetch table provider for 'hello': Not a Delta table: No snapshot or version 0 found, perhaps memory://databases/00000000-0000-0000-0000-000000000000/tables/20000 is an empty dir?

**Comment by vrongmeal** [comment]
I think this is specific to when engine storage is in memory.

**Comment by vrongmeal** [comment]
We get nothing when trying to query an empty table because it's an empty directory. I think, in this case, we do want to return an empty record batch with the schema that we have from the metastore. A simpler way would be to create an empty data file with the correct schema when the table is created, not sure if that's actually easy to implement.

**Comment by adhish20** [comment]
Adding an empty row with the correct schema does not fix this. The issue is across sessions, we are not able to load the table location due to missing commit log/snapshot on delta-rs end.
