### ISSUE TITLE
`psql` hangs forever when `--ignore-pg-auth` is passed to local server

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1663]
**Terminal 1**:

```shell
$ cargo run --bin glaredb -- server --ignore-pg-auth
```

**Terminal 2**:

```shell
$ psql "host=localhost user=glaredb dbname=glaredb port=6543"
```

**Comment by greyscaled** [comment]
@scsmithr we used to use it to develop cloud, so I want to say yes.

**Comment by vrongmeal** [comment]
The problem lies here:

https://github.com/GlareDB/glaredb/blob/34556af7d4d85ccbfaac65eb17e5c96a5532b180/crates/pgsrv/src/handler.rs#L222-L237

We don't get any authentication message we can drop, so the connection hangs on `peek`, where it keeps waiting for a message, just any message and not just auth.

As I understand, this is simply for ignoring node-postgres auth messages:

```rust
         /// A compliant frontend should not send any additional authentication
         /// messages after receiving AuthenticationOk. However, node-postgres
         /// will attempt to send a password message regardless. Setting this to
         /// true will drop that message.
```

What we want to do here is `try_peek` (sync), which checks if there's a message to read and moves on if there's none. We shouldn't `await` for a new message. I am not sure if this would work, @scsmithr you might have a better idea about it but I assume, this is how the `node-postgres` is sending messages.

**Comment by vrongmeal** [comment]
A more straightforward solution would be to send the `BackendMessage::AuthenticationCleartextPassword` every time (when `--ignore-pg-auth`). This requires us to send a dummy password whenever prompted.
