### ISSUE TITLE
RuntimeGroupExec not pulled up through FilterExec

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1754]
## Description

For this query:

```
select count(*) as query_count,
       max(e.elapsed_compute_ns) as max_elapsed
  from bq_segment.glaredb_prod.execution_metric e 
  inner join pg_prod.public.users u on e.user_id = u.id
  inner join users u2 on u.email = u2.email
  where e.timestamp::timestamp > now() - interval '3 day'
```

The `RemoteScanExec` is for the bigquery table `bq_segment.glaredb_prod.execution_metric`.

```
│               │                                 FilterExec: timestamp@1 > 1694262538161859386                                                           │
│               │                                   RuntimeGroupExec: runtime_preference=remote                                                           │
│               │                                     RepartitionExec: partitioning=RoundRobinBatch(8), input_partitions=1                                │
│               │                                       RemoteScanExec: projection=[elapsed_compute_ns, timestamp, user_id] 
```

**Comment by scsmithr** [comment]
Tentatively set aside for @gruuya

**Comment by gruuya** [comment]
> This is actually because we're only pulling up once and not as many times as possible...
> 
> https://github.com/glaredb/glaredb/blob/244817e6394f31eccb1de98b1830a39b2c91c14c/crates/datafusion_ext/src/runtime/group_pull_up.rs#L94-L136

I tested this, and it seems the pull-ups occur more than once when applicable, i.e. when a plan commutes with `RuntimeGroupExec`, see 17327aa37f507ece4c7943c1ba2e2ceaeb757de8 for an example. This is to be expected since `TreeNode::transform_up` does a postorder traversal, so it should be applying the transformation from the leaf nodes up.

This does leave the question why `RuntimeGroupExec` wasn't pulled up through `FilterExec` in the above example. It could be an interference from some other DF plan optimizations, e.g. due to re-partitioning or the joins. Looking into this further.

**Comment by gruuya** [comment]
Oh I think I see now what's going on here. In essence the `EXPLAIN` is pulling a trick. Since the optimizer is trying to perform a postorder traversal it starts off by asking for the children of the root node, which in the above case is `ExplainExec` which has no children by design
https://github.com/apache/arrow-datafusion/blob/44b3318c2a13777ca309e46d06a8022b712d209f/datafusion/physical-plan/src/explain.rs#L98-L101 

So the optimizer never runs and we see the misleading output. To verify that the optimizer does indeed run as expected in the absence of the `EXPLAIN` (i.e. when the actual query is run) we can do something like:
```diff
diff --git a/crates/datafusion_ext/src/runtime/group_pull_up.rs b/crates/datafusion_ext/src/runtime/group_pull_up.rs
index d05decc..2be2c75 100644
--- a/crates/datafusion_ext/src/runtime/group_pull_up.rs
+++ b/crates/datafusion_ext/src/runtime/group_pull_up.rs
@@ -92,7 +92,7 @@ impl PhysicalOptimizerRule for RuntimeGroupPullUp {
         plan: Arc<dyn ExecutionPlan>,
         _config: &ConfigOptions,
     ) -> Result<Arc<dyn ExecutionPlan>> {
-        plan.transform_up(&|plan| {
+        let plan = plan.transform_up(&|plan| {
             if !can_pull_through_node(plan.as_ref()) {
                 return Ok(Transformed::No(plan));
             }
@@ -134,7 +134,11 @@ impl PhysicalOptimizerRule for RuntimeGroupPullUp {
                 preference,
                 child: node,
             })))
-        })
+        })?;
+
+        println!("{plan:#?}");
+
+        Ok(plan)
     }

     fn name(&self) -> &str {
```

And then when we run the query
```sql
> select count(*) as query_count,
:::        max(e.elapsed_compute_ns) as max_elapsed
:::   from bq.glaredb_qa.execution_metric e
:::   -- inner join qa.public.users u on e.user_id = u.id
:::   -- inner join users u2 on u.email = u2.email
:::   where e.timestamp::timestamp > now() - interval '3 day';
ProjectionExec {
    expr: [
        (
            Column {
                name: "COUNT(UInt8(1))",
                index: 0,
            },
            "query_count",
        ),
        (
            Column {
                name: "MAX(e.elapsed_compute_ns)",
                index: 1,
            },
            "max_elapsed",
        ),
    ],
...
                    input: CoalesceBatchesExec {
                        input: RuntimeGroupExec {
                            preference: Remote,
                            child: FilterExec {
                                predicate: BinaryExpr {
                                    left: Column {
                                        name: "timestamp",
                                        index: 1,
                                    },
                                    op: Gt,
                                    right: Literal {
                                        value: TimestampNanosecond(1694792651340030000, Some("UTC")),
                                    },
                                },
                                input: RepartitionExec {
                                    input: RemoteScanExec {
                                        provider: ProviderReference::RemoteReference(432a97e6-85ce-4622-8ab2-81f9f8c33892),
                                        projected_schema: Schema {
                                            fields: [
                                                Field {
                                                    name: "elapsed_compute_ns",
 ...




┌─────────────┬─────────────┐
│ query_count │ max_elapsed │
│          ── │          ── │
│       Int64 │       Int64 │
╞═════════════╪═════════════╡
│           2 │        NULL │
└─────────────┴─────────────┘
```
You can see that indeed the `RuntimeGroupExec` is pulled over the `FilterExec`, but not `CoalesceBatchesExec`, which it doesn't commute with (though I think we could change that?).

The only work item I see left here is to fix the `RuntimeGroupPullUp` optimizations rule so that it doesn't "mask" its behavior when used in conjunction with `Explain`.

**Comment by scsmithr** [comment]
Nice debugging on this.

> You can see that indeed the RuntimeGroupExec is pulled over the FilterExec, but not CoalesceBatchesExec, which it doesn't commute with (though I think we could change that?).

Pulling up through CoalesceBatchesExec would make sense to me, was an oversight on not including that.

> The only work item I see left here is to fix the RuntimeGroupPullUp optimizations rule so that it doesn't "mask" its behavior when used in conjunction with Explain.

This sounds good. Happy that this is working as expected and just requires that we present it appropriately.
