### ISSUE TITLE
Validate storage options when creating a Delta/Iceberg table in an object store

### ISSUE THREAD

**Issue by gruuya** [GlareDB/glaredb#1817]
## Description

Could be done via a HEAD request, however the `location` option provided in such a case is a directory path, and not a concrete object, so this won't work.

On the other hand `list`-ing from the table root dir could be an overkill/expensive.

**Comment by scsmithr** [comment]
For delta, I think `load_table_direct` should be sufficient since it would be reading just metadata.

And for iceberg, `IcebergeTable::open(..)` should good too since that's just metadata as well.

Both of these would also validate that the table root is actually of the correct type too (delta/iceberg).

**Comment by gruuya** [comment]
Good idea, will add that now, prior to #1806.
