### ISSUE TITLE
Ensure float size is correct when encoding to pg values

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1921]
## Description

See https://github.com/PRQL/prql/pull/3669#issuecomment-1762545507

It looks like we're passing Float8 in the postgres row descriptor, but the column values are actually f32.

I don't have a reproducible sql example yet...

**Comment by vrongmeal** [comment]
TL;DR: We don't support binary formatting as of now.

Querying using the rust client (`query` method) assumes the data we `get` is in binary format, but currently, we only support text format.

```rust
let rows = client.query("select 11111111", &[]).await?;
let val: i64 = rows[0].get(0);
```

The above code works since the string `11111111` has 8 bytes (equivalent to `int8`). Any other string length would fail.


This would work if the test uses `simple_query` and parse the string as `f64` but that would require implementing a different test client in prql.

**Comment by eitsupi** [comment]
Thanks for looking at this! Maybe this issue sfackler/rust-postgres#882?

**Comment by vrongmeal** [comment]
> Thanks for looking at this! Maybe this issue https://github.com/sfackler/rust-postgres/issues/882?

Yeah, this issue is related.
