### ISSUE TITLE
prql python function

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2011]
## Description

E.g. 

```python
import glaredb

con = glaredb.connect()
con.prql('<my prql query>').show()
```

This would bypass checking the `dialect` variable and always compile the prql.

**Comment by tychoish** [comment]
I sort of imagined that we'd build this as just a wrapper around our `sql` method, so that the client (or at least the python binary) wouldn't need to have PRQL around locally; but of course it must so that it can work in the fully local mode. 

I then envisioned that we might want to have a python library that was just a pure library without any of the local tooling just to get something minimal, and while we might want to do that, we'd probably just write that on top of pure-grpc clients (potentially still in rust, but who knows) rather than starting with the current python bindings, but who knows. In either case, that's something that is a ways off right now. 

The current proposed solution (translate PRQL in the python bindings) in light of that sounds good.
