### ISSUE TITLE
Chore: node bindings dx

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2063]
## Description

Now that we have the framework for the node bindings in, next steps are ensuring a good experience when developing the bindings. This issue tries to list out the paper cuts we have right now.

- Document how to run the example script.

Running `node example.js` results in an error about it having an `import` and that we need to rename with a `.mjs` extension or update the `package.json`. Should we do that, or should be be running the example differently.

- Debug SIGABRT when running adding additional tests

Currently hitting a `abort trap: 6` on npm and `error Command failed with signal "SIGABRT".` on yarn. Currently unknown what's causing this

**Comment by universalmind303** [comment]
> Running node example.js results in an error about it having an import and that we need to rename with a .mjs 

honestly I just run it with [bun](https://bun.sh/). It's soo much easier than dealing with module imports & the terrible node ecosystem.

**Comment by universalmind303** [comment]
Originally I was using the `example` file for testing purposes. Honestly, I didn't realize I committed it until you opened this issue. 

> Running node example.js results in an error about it having an import and that we need to rename with a .mjs extension or update the package.json. Should we do that, or should be be running the example differently.

This is just node specific BS. Somehow, node still can't natively handle `import` statements without using either custom extensions or transpilation. 

I've since just started using [bun](https://bun.sh/) as it all works out of the box. I highly recommend it.

Otherwise, we can replace the example with commonjs compatible code.

```js
const glaredb = require('./glaredb.js');

async function main() {
    let con = await glaredb.connect();
    let res = await con.sql("select * from '../testdata/json/userdata1.json' limit 1");
    let df = await res.toPolars();
    console.log("polars\n---\n ", df.toString());
}

main().catch(console.error);
```

**Comment by tychoish** [comment]
I think it'd be good to be able to run the example file with nothing special required even if it's not great.
