### ISSUE TITLE
SQLServer SLT test flake

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2434]
## Description

```
Run ./scripts/prepare-testdata.sh
Attempting to pull glaredb-testdata/bikeshare_trips.csv into testdata/sqllogictests_datasources_common/data/gcs-artifacts/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 92  187M   92  173M    0     0   214M      0 --:--:-- --:--:-- --:--:--  214M
100  187M  100  187M    0     0   220M      0 --:--:-- --:--:-- --:--:--  220M
./target/debug/glaredb sql-logic-tests sqllogictests_sqlserver/*
sh: 1: ./target/debug/glaredb: not found
error: Recipe `slt-bin` failed on line 69 with exit code 127
Error: Process completed with exit code 127.
```

https://github.com/GlareDB/glaredb/actions/runs/7546238252/job/20543641397?pr=2433

**Comment by tychoish** [comment]
This looks like a cache bug: the glaredb binary wasn't there, so it's not related to SQLServer as such. Looking at the [logs](https://github.com/GlareDB/glaredb/actions/runs/7546238252/job/20543641397?pr=2433#step:4:9) it does seem like a cache bug, but the [corresponding cache population task](https://github.com/GlareDB/glaredb/actions/runs/7546238252/job/20543580219?pr=2433#step:12:5) looks like it worked. 

Is it possible that we have a task that removes the glaredb binary, which is then cached, somehow? Otherwise it sort of seems like a CI bug, and we should probably just monitor and see if this kind of thing happens more.

**Comment by tychoish** [comment]
We've done a bunch of cleanup to the CI system handles caching recently, and I haven't seen anything like this, so I'm inclined to close (which probably means we'll hit it again tomorrow) for now.
