### ISSUE TITLE
Feat: `read_uploads` table func

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2614]
## Description

Motivation: Allow users to query files they've uploaded while making use of our existing credentials setup.

What this would look like for the end user:

```sql
select * from stage.'my_file.csv';
```

- `stage` as the schema name is tbd
- 'my_file.csv' is the file the user uploaded in cloud

Implementation:
- New builtin schema (stage).
  - Users should not be able to create objects in this schema.
- Extend external dispatching rules to check the `stage` schema, dispatch to user files as appropriate.
  - Likely extension point: https://github.com/glaredb/glaredb/blob/7c4270c1334cbcee052fd264ac76b1a496d74243/crates/sqlexec/src/dispatch/external.rs#L95-L131
  - This should use the object store that we create on the `NativeTableStorage` since that will have the credentials already configured for the user bucket.
  - We'll need to thread stuff down related to the bucket/location of user files.

Future:
- Make `stage` an implicit schema such that `select * from 'my_file.csv'` would resolve to the user file.

**Comment by greyscaled** [comment]
Question, would we eventually support `DROP TABLE stage.<my_file>` ?

**Comment by greyscaled** [comment]
We:

- decided on not adding the `glare_uploads` schema
- will add a table func `read_uploads(filename, filetype)`

**Comment by tychoish** [comment]
I like the tablefunc idea a lot and it's such a good starting point. 

I the the only thing I'd change is that it probably wants to be `read_upload` rather than "uploads". 

I keep playing in my mind with some alternate text (because this isn't quite like the other table-funcs so maybe it's fine that it's not `read_`) that takes advantage of being in a `FROM` clause, as in `SELECT * FROM glare_upload(<path>)`

Let me know if you want to pair on this grey.

**Comment by greyscaled** [comment]
> I the the only thing I'd change is that it probably wants to be `read_upload`

Yea, I think the 's' was accidental, +1 for `upload`


> I keep playing in my mind with some alternate text (because this isn't quite like the other table-funcs so maybe it's fine that it's not `read_`) that takes advantage of being in a `FROM` clause, as in `SELECT * FROM glaredb_upload(<path>)`

Worth playing around with and finding what feels best. I'm generally happy with things that have a `glare_` prefix (instead of `glaredb_`), though maybe it's beneficial to keep this one `read_` for symmetry with our other table funcs - I'm unsure.

In some ways, it almost has me thinking that like we could extend our existing table funcs since this one is really doing the same thing, but in a designated location. This is a top-of-mind spitball, but imagine:

```sql
select * from read_csv('glare_uploads/hello.csv');
select * from read_parquet('glare_uploads/my-file');
```

If those are too magical, there's an option to add a `location` or similarly named option:

```sql
select * from read_csv('hello.csv', location => glare_uploads);
```


> Let me know if you want to pair on this grey.

Sounds good

**Comment by tychoish** [comment]
I like having this as a separate table function for the moment and adding magic in to other table funcs later if needed/wanted.
