### ISSUE TITLE
support reading excel files from object storage.

### ISSUE THREAD

**Issue by tychoish** [GlareDB/glaredb#2645]
Could use the GenericStoreAccess as [here](https://github.com/glaredb/glaredb/blob/main/crates/sqlbuiltins/src/functions/table/bson.rs#L52-L79).

**Comment by hemanth94** [comment]
Hello @tychoish 
I think, adding Object_Store support to excel may not be as simple as you assumed.

Since the  [code here](https://github.com/GlareDB/glaredb/blob/9b8483fb5a1cd63476efc5132468378e30323587/crates/datasources/src/excel/mod.rs#L156) written to read excel is only applicable for local files. 

I didn't find any code similar to [Bson Object_Store implementation](https://github.com/GlareDB/glaredb/blob/9b8483fb5a1cd63476efc5132468378e30323587/crates/datasources/src/bson/table.rs#L50-L70) written which i could replicate to excel.

Please correct me if I'm missing something. Can i try writing code for this?

Thanks,

**Comment by tychoish** [comment]
This was done in #2684
