### ISSUE TITLE
(mongo): Convert timestamps to nanoseconds

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#722]
## Context

https://github.com/glaredb/glaredb/blob/0b27679f92851452307283cb204f9519657e6448/crates/datasource_mongodb/src/infer.rs#L93-L96

Mongo returns seconds/microseconds depending on the type. We should be converting everything to nanoseconds to be inline with the other datasources we support.

## Expected

Match timestamps with other data sources.

## Actual

Kinda just do whatever right now.

**Comment by tychoish** [comment]
There are three data types that store times in BSON:
- object_id's (second resolution since unix epoch, used for primary key in index, not really used to track time typically, shouldn't convert, or provide a native oid interface) 
- timestamps (used internally for the operation logs, most important property is that it's monotonic, low resolution, you'd have to either be parsing the oplog to tail replication, or construct the bson documents very carefully by hand). I think doing second-level on these is fine, and they're def legacy. 
- datetime: this is the primary date-type, and it has milisecond resolution.

For nanosecond resolution, you'd have to build your own type (or just store int64s) and convert it after the fact, and I'm not sure there's a clear answer of what to do here. 

Questions:
- if we have a nanosecond timestamp and we're writing it to mongodb, do we trim to miliseconds, or save it as an int64 and lose the ability to round trip? (as far as I know postgres timestamps are also in millis so we should just do whatever we do there?)
- ...

**Comment by tychoish** [comment]
I cleaned this up as part of a previous PR to something that's "more canonical bson" and I think it's good enough in it's current form.
